model:
  base_learning_rate: 1.0e-05
  pretrained_model: pretrained_models/paint-11channels.ckpt
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: "composition"
    cond_stage_key: "image"
    image_size: 64
    channels: 4
    cond_stage_trainable: False   # Note: different from the one we trained before
    finetune_full_unet: True
    augment_config: &augment_config
      augment_types: [ [0,0], [1,0] ]
      sample_prob: [ 0.5, 0.5 ]
      sample_mode: random # all
      augment_box: False
      augment_background: True
      replace_background_prob: 1
      use_inpaint_background: False
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    u_cond_percent: 0.2
    scale_factor: 0.18215
    use_ema: True
    use_guidance: true
    local_uncond: same # choose from [learnable, single_learnable, zero, same]

    scheduler_config: # 10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [ 1000 ]
        cycle_lengths: [ 10000000000000 ] # incredibly large number to prevent corner cases
        f_start: [ 1.e-6 ]
        f_max: [ 1. ]
        f_min: [ 1. ]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 11
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
        add_conv_in_front_of_unet: False
        local_encoder_config:
          conditioning_key: ldm.modules.local_module.LocalRefineBlock
          add_position_emb: false
          roi_size: 16
          context_dim: 1024
          resolutions: [1, 2]
          add_in_encoder: true
          add_in_decoder: true
          add_before_crossattn: false
    
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPImageEmbedder
      params:
        local_hidden_index: 12
        use_foreground_mask: False
        patchtoken_for_global: False

data:
  target: ldm.data.datamodule.DataModuleFromConfig
  dataset_dir: &dataset_dir ../../dataset/open-images
  params:
      batch_size: 16
      num_workers: 16
      wrap: False
      train:
          target: ldm.data.open_images_control.OpenImageDataset
          params:
              split: train
              dataset_dir: *dataset_dir
              image_size: 512
              augment_config: *augment_config
      validation:
          target: ldm.data.open_images_control.COCOEEDataset
          params:
              split: test
              dataset_dir: ../../dataset/cocoee
              image_size: 512
              augment_config: *augment_config
      # validation:
      #     target: ldm.data.open_images_control.OpenImageDataset
      #     params:
      #         split: validation
      #         dataset_dir: *dataset_dir
      #         image_size: 512 
      #         augment_config: *augment_config
      test:
          target: ldm.data.open_images_control.OpenImageDataset
          params:
              split: test
              dataset_dir: *dataset_dir
              image_size: 512 
              augment_config: *augment_config

lightning:
  trainer:
    max_epochs: 20
    accelerator: gpu
    devices: 8
    num_nodes: 1
    val_check_interval: 1.0